public class MathOperationUtility 
{
	Public static void Addition (integer x,integer y,integer z)
    {
        System.debug('Addition Result are.......:'+( x + y + z ));
    }
    Public static void Subtraction (integer x, integer y)
    {
        System.debug('Subtraction Result are......:'+( x - y));
    }
    Public Static void multiply(integer x,integer y,integer z)
    {
        System.debug('Multiply Result are.....:'+( x * y * z));
    }
    public static void Division (integer x,integer y)
    {
        System.debug('Division are....:'+( x / y ));
    }
    public static void Module(integer x,integer y)
    {
        System.debug('Module Result are......:'+ ( math.mod(x, y)));
    }
}