import { createElement } from 'lwc';
import SFDX_01_LWC_Accordion_Eg_01 from 'c/sFDX_01_LWC_Accordion_Eg_01';

describe('c-s-f-d-x-01-l-w-c-accordion-eg-01', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-s-f-d-x-01-l-w-c-accordion-eg-01', {
            is: SFDX_01_LWC_Accordion_Eg_01
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});